# Generated by Django 3.2.18 on 2023-05-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='accounts/blank.png', upload_to=''),
        ),
    ]
