# Generated by Django 3.2.18 on 2023-05-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommend_movies',
            field=models.ManyToManyField(related_name='recommends', to='movies.Movie'),
        ),
    ]
